rules:
  default:
    protection:
      required_pull_request_reviews:
        required_approving_review_count: null
      required_status_checks:
        contexts:
          - continuous-integration/travis-ci
  branches:
    automerge:
      protection:
        required_pull_request_reviews: null
        required_status_checks:
          contexts:
            - continuous-integration/travis-ci
