pull_request_rules:
  - name: automatic merge
    conditions:
      - base=master
      - status-success=continuous-integration/travis-ci/pr
      - label!=work-in-progress
      - "#approved-reviews-by=0"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - "#commented-reviews-by=0"
    actions:
      merge:
        strict: "smart"
        method: rebase
