pull_request_rules:
  - name: automatic merge
    conditions:
      - base=master
      - status-success=continuous-integration/travis-ci/pr
      - label!=work-in-progress
    actions:
      merge:
        strict: "smart"
        method: rebase
